name: Backend CI

on:
  push:
    branches:
      - "**"
    paths:
      - 'backend/**'
      - .github/workflows/ci-backend.yml

jobs:
  qa:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Configure cache
        id: python-cache
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: |
            ${{ env.pythonLocation}}
          key: v2-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
      - name: Install deps using Pip
        run: pip install -r requirements-dev.txt
        if: steps.python-cache.outputs.cache-hit != 'true'
      - name: Run linting checks
        run: |
          isort scaife_stack_atlas -rc --check-only
          black scaife_stack_atlas --check
          flake8 scaife_stack_atlas
      - name: Run tests
        run: pytest
  build-and-push-images:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prep Tag Data
        id: tags
        run: |
          export REF=${GITHUB_REF#refs/*/};
          export VERSION=${REF//[^[:alpha:][:digit:]\.\-\_]/};
          echo "::set-output name=version::$VERSION";
          echo "::set-output name=minor::${VERSION%.*}.x";
          echo "::set-output name=major::${VERSION%.*.*}.x.x";
          echo "::set-output name=sha7::${GITHUB_SHA::7}";

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GH Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Images
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: heroku.dockerfile
          push: true
          # Tag :branchname, and :commit-sha
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tags.outputs.version }}
            ghcr.io/${{ github.repository }}:${{ steps.tags.outputs.sha7 }}
            ghcr.io/${{ github.repository }}:latest
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            GIT_VERSION=${{ github.ref }}
            VERSION=${{ steps.tags.outputs.sha7 }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
